apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-guestbook
  namespace: argo-cd
spec:
  destination:
    namespace: helm-guestbook
    server: "https://kubernetes.default.svc"
  project: default
  source:
    path: helm-guestbook
    repoURL: "https://github.com/devopstia/argocd-example-apps.git"
    targetRevision: master
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - Prune=true
  # Specify the Helm chart values file to use.
  helm:
    valueFiles:
      - ./tia/helm-guestbook.yaml # Reference the Helm values file





  helm:
    values: tia/helm-guestbook.yaml # Reference the Helm values file
